services:
  basededatos:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: tienda
      POSTGRES_USER: erick
      POSTGRESS_PASSWORD: 1234
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: